[package]
name = "field-collex"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Collections implemented on block-based idea . (Do not ask me why `Field` ;> )"
repository = "https://github.com/Milk-COCO/field-collex"

[dependencies]
num-traits = "^0.2"
fraction = "^0.15"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
